<script lang="ts">
	import { scrollPos } from '$lib/store';

	let { posts, number }: { posts: { title: string; body: string }[]; number: number } = $props();

	let rots = [1.6, -1.2, 1.3, -1.5];
	let box: HTMLElement = $state();

	let offset = $state(box ? (box.clientHeight - 10) * number : 0);

	$effect(() => {
		box.scrollTop = $scrollPos + offset;
		if (number === 0) {
			console.log(number, box.scrollTop, $scrollPos, $scrollPos + offset);
		}
	});
	$effect(() => {
		// box.scrollTop = $scrollPos;
		offset = box ? (box.clientHeight - 10) * number : 0;
		console.log(number, offset, box.scrollTop);
	});
	let done = $state(false);
	$effect(() => {
		if (box && !done) {
			box.appendChild(box.firstElementChild.cloneNode(true));
			box.scrollTop = 0;
			box.scrollTop = 1;
			const childHeight = box.firstElementChild.clientHeight;
			let scrollAmount = box.scrollHeight - childHeight;
			box.scrollTop = scrollAmount + offset;
			$scrollPos = scrollAmount - 100;
			box.addEventListener('scroll', scrollListener);
			console.log('added');
			done = true;
		}
	});

	// https://jsfiddle.net/byeam39o/2/
	function scrollListener(e) {
		let scrollAmount = 0;

		const totalHeight = e.target.scrollHeight; // Total height of scrollable content
		const scrollLocation = Math.round(e.target.scrollTop); // Amount scrolled
		const containerHeight = e.target.clientHeight; // Size of element
		// If bottom reached
		if (totalHeight - scrollLocation <= containerHeight) {
			scrollAmount = 1; // If top reached
			e.target.scrollTop = scrollAmount + offset;
			$scrollPos = scrollAmount;
		} else if (scrollLocation === 0) {
			const childHeight = box.firstElementChild.clientHeight;
			scrollAmount = totalHeight - childHeight;
			e.target.scrollTop = scrollAmount + offset;
			$scrollPos = scrollAmount;
		}
		$scrollPos = e.target.scrollTop - offset;
	}
</script>

<div
	class="scroll"
	style=" left:{number * 25}dvw; rotate:{rots[number]}deg; z-index:{5 - number};"
	bind:this={box}
	class:hidden={!done}
>
	<div class="content">
		{#each posts as post, i}
			{#if i == 0 || i % 5 == 0}
				<div class="about">
					<div class="line"></div>
					<h1>AI Fixed My Relationship</h1>
					<strong
						>This is a collection of texts generated by a Markov chain trained on 2913007 tokens
						scraped from AI related posts found on various relationship focused Subreddits.</strong
					>
					<p>Created by <a href="https://www.fredwordie.com/" target="_blank">Fred Wordie</a></p>
					<p>
						See the
						<a href="https://github.com/fwordie/reddit-markov-chain" target="_blank">Code</a>
					</p>
					<div class="line"></div>
				</div>
			{/if}
			<div class="post">
				<h3>{post.title}</h3>
				<p>{post.body}</p>
			</div>
		{/each}
	</div>
</div>

<style lang="scss">
	.scroll {
		margin-inline: -10px;
		padding-inline: 20px;
		border-left: 1px solid black;
		border-right: 1px solid black;
		max-height: calc(100dvh + 20px);
		margin-top: -10px;
		overflow-y: scroll;
		overflow-x: hidden;
		background-color: white;
		scrollbar-width: none;
		-ms-overflow-style: none;
		opacity: 1;
		::-webkit-scrollbar {
			display: none;
		}
	}
	.hidden {
		opacity: 0;
	}
	h3 {
		margin-bottom: 5px;
	}
	p {
		white-space: pre-wrap;
		margin-top: 5px;
	}
	.about {
		margin-block: 40px;
		.line {
			margin-block: 20px;
			width: 100%;
			border-top: dotted 2px black;
		}
		h1{
		margin-top: 0px;
		}
		p {
			margin: 0px;
			margin-block: 0.2em;
			white-space: normal;
		}
	}
</style>
